# Generated by Django 3.2.8 on 2024-10-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nombre', max_length=100)),
                ('descripcion', models.CharField(default='Descripción por defecto', max_length=250)),
                ('image', models.ImageField(default='imagenes/default.jpg', upload_to='imagenes/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
