# Generated by Django 3.2.8 on 2024-10-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_cliente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
